### ISSUE TITLE
use bytes not necessary

### ISSUE THREAD

**Issue by erantapaa** [plainblack/JSON-RPC-Dispatcher#2]
I don't think you need to "use bytes".

It seems that the only place where any built-in functions affected by 'use bytes' is used is on this line:

```
    $response->content_length(bytes::length($json));
```

However, $json comes from JSON->new->utf8->encode(...), and therefore it is guaranteed to be a byte string - i.e. the UTF-8 flag will not be set.

If you feel you still need to use bytes, consider isolating it to the smallest necessary lexical scope, i.e. something like:

```
    { use bytes; $response->content_length(bytes::length($json) };
```

**Comment by davehamptonusa** [comment]
That won't actually do anything.  `use` statements are elevated to the `BEGIN` block.  So whether a `use` is in a condition or block, its still loaded first.

`require` will avoid that, but its still going to be loaded, so scoping doesn't make a difference.

**Comment by dmcbride** [comment]
@davehamptonusa yes, use loads it first, but the import will be called within the scope given, much like `use warnings` (or `no warnings`).

**Comment by dmcbride** [comment]
```
use 5.12.1;
use utf8;
use JSON;

my $o = {name => "Sābēn Demesne \u3042" . chr hex 3042};
say $o->{name};

my $j = JSON->new->utf8->encode($o);
require bytes;

say $j;
say length($j);
say bytes::length($j);
say utf8::is_utf8($j) ? "yes" : "no";
say utf8::is_utf8($o->{name}) ? "yes" : "no";
```

This seems to confirm what @erantapaa is saying.  Thus I'm inclined to remove the bytes altogether.
